/*
 * Copyright (c) 2023, Intercreate, Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright (c) 2019 Oticon A/S:
 *      https://github.com/zephyrproject-rtos/zephyr/blob/4d10c960da80baf81e6d6be0c515fd7237fcb7ef/tests/unit/util
 *      SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2023 Meta
 *      https://github.com/zephyrproject-rtos/zephyr/blob/4d10c960da80baf81e6d6be0c515fd7237fcb7ef/tests/unit/pot
 *      SPDX-License-Identifier: Apache-2.0
 */

#include <unity.h>

void setUp(void) {} /* Is run before every test, put unit init calls here. */
void tearDown(void) {} /* Is run after every test, put unit clean-up calls here. */

#include <fff.h>

#include "helpers.h"
DEFINE_FFF_GLOBALS;

#include <ic_macros.h>

void test_IC_ABS(void) {
    IC_ASSERT_CONSTANT(IC_ABS(0));

    TEST_ASSERT_EQUAL(0, IC_ABS(0));
    TEST_ASSERT_EQUAL(1, IC_ABS(1));
    TEST_ASSERT_EQUAL(1, IC_ABS(-1));
    TEST_ASSERT_EQUAL(1.f, IC_ABS(1.f));
    TEST_ASSERT_EQUAL(1.f, IC_ABS(-1.f));
    TEST_ASSERT_EQUAL(1., IC_ABS(1.));
    TEST_ASSERT_EQUAL(1., IC_ABS(-1.));
    TEST_ASSERT_EQUAL(2147483647L, IC_ABS(-2147483647L));  // i32
    TEST_ASSERT_EQUAL(9223372036854775807LL, IC_ABS(-9223372036854775807LL));  // i64
}


void test_IC_IROUND_UP(void) {
    IC_ASSERT_CONSTANT(IC_IROUND_UP(0, 1));

    TEST_ASSERT_EQUAL(0, IC_IROUND_UP(0, 1));
    TEST_ASSERT_EQUAL(0, IC_IROUND_UP(0, 3));
    TEST_ASSERT_EQUAL(0, IC_IROUND_UP(0, 4));
    TEST_ASSERT_EQUAL(0, IC_IROUND_UP(0, 32));

    TEST_ASSERT_EQUAL(1, IC_IROUND_UP(1, 1));
    TEST_ASSERT_EQUAL(3, IC_IROUND_UP(1, 3));
    TEST_ASSERT_EQUAL(4, IC_IROUND_UP(1, 4));
    TEST_ASSERT_EQUAL(32, IC_IROUND_UP(1, 32));

    TEST_ASSERT_EQUAL(-1, IC_IROUND_UP(-1, 1));
    TEST_ASSERT_EQUAL(0, IC_IROUND_UP(-1, 3));
    TEST_ASSERT_EQUAL(0, IC_IROUND_UP(-1, 4));
    TEST_ASSERT_EQUAL(-32, IC_IROUND_UP(-32, 32));
    TEST_ASSERT_EQUAL(-32, IC_IROUND_UP(-63, 32));

    TEST_ASSERT_EQUAL(9223372036854775807LL, IC_IROUND_UP(9223372036854775807LL, 1));
}


void test_IC_CEIL(void) {
    IC_ASSERT_CONSTANT(IC_CEIL(0.1));

    TEST_ASSERT_EQUAL_DOUBLE(1., IC_CEIL(0.1));
    TEST_ASSERT_EQUAL(1, IC_REQUIRE_CONSTANT((int) IC_CEIL(0.1)));

    TEST_ASSERT_EQUAL_DOUBLE(-1., IC_CEIL(-1.1));
    TEST_ASSERT_EQUAL(-1, IC_REQUIRE_CONSTANT((int) IC_CEIL(-1.1)));

    TEST_ASSERT_EQUAL_FLOAT(1.f, IC_CEIL(0.1f));
    TEST_ASSERT_EQUAL(1, IC_REQUIRE_CONSTANT((int) IC_CEIL(0.1f)));

    TEST_ASSERT_EQUAL_DOUBLE(100000., IC_CEIL(99999.00000001));
    TEST_ASSERT_EQUAL(100000, IC_REQUIRE_CONSTANT((int) IC_CEIL(99999.00000001)));

    TEST_ASSERT_EQUAL_DOUBLE(100000.l, IC_CEIL(99999.00000001l));
    TEST_ASSERT_EQUAL(100000, IC_REQUIRE_CONSTANT((int) IC_CEIL(99999.00000001l)));

    TEST_ASSERT_EQUAL_FLOAT(10000.f, IC_CEIL(9999.001f));
    TEST_ASSERT_EQUAL(10000, IC_REQUIRE_CONSTANT((int) (IC_CEIL(9999.001f))));

    TEST_ASSERT_EQUAL_FLOAT(9999.f, IC_CEIL(9999.f));
    TEST_ASSERT_EQUAL(9999, IC_REQUIRE_CONSTANT((int) (IC_CEIL(9999.f))));
}

void test_IC_FLOOR(void) {
    IC_ASSERT_CONSTANT(IC_FLOOR(0.));

    TEST_ASSERT_EQUAL_DOUBLE(0., IC_FLOOR(0.9));
    TEST_ASSERT_EQUAL(0, IC_REQUIRE_CONSTANT((int) IC_FLOOR(0.9)));

    TEST_ASSERT_EQUAL_DOUBLE(-1., IC_FLOOR(-0.9));
    TEST_ASSERT_EQUAL(-1, IC_REQUIRE_CONSTANT((int) IC_FLOOR(-0.9)));

    TEST_ASSERT_EQUAL_FLOAT(0.f, IC_FLOOR(0.9f));
    TEST_ASSERT_EQUAL(0, IC_REQUIRE_CONSTANT((int) IC_FLOOR(0.9f)));

    TEST_ASSERT_EQUAL_DOUBLE(100000., IC_FLOOR(100000.00000001));
    TEST_ASSERT_EQUAL(100000, IC_REQUIRE_CONSTANT((int) IC_FLOOR(100000.00000001)));

    TEST_ASSERT_EQUAL_DOUBLE(100000.l, IC_FLOOR(100000.00000001l));
    TEST_ASSERT_EQUAL(100000, IC_REQUIRE_CONSTANT((int) IC_FLOOR(100000.00000001l)));

    TEST_ASSERT_EQUAL_FLOAT(10000.f, IC_FLOOR(10000.001f));
    TEST_ASSERT_EQUAL(10000, IC_REQUIRE_CONSTANT((int) (IC_FLOOR(10000.001f))));

    TEST_ASSERT_EQUAL_FLOAT(10000.f, IC_FLOOR(10000.f));
    TEST_ASSERT_EQUAL(10000, IC_REQUIRE_CONSTANT((int) (IC_FLOOR(10000.f))));
}

void test_IC_ROUND(void) {
    IC_ASSERT_CONSTANT(IC_ROUND(0.5));

    TEST_ASSERT_EQUAL_TYPE(double, IC_ROUND(0.5));
    TEST_ASSERT_EQUAL_TYPE(float, IC_ROUND(0.5f));
    TEST_ASSERT_EQUAL_TYPE(long double, IC_ROUND(0.5l));

    TEST_ASSERT_EQUAL_DOUBLE(0., IC_ROUND(0.49));
    TEST_ASSERT_EQUAL(0, IC_REQUIRE_CONSTANT((int) IC_ROUND(0.49)));
    TEST_ASSERT_EQUAL_DOUBLE(1., IC_ROUND(0.5));
    TEST_ASSERT_EQUAL(1, IC_REQUIRE_CONSTANT((int) IC_ROUND(0.5)));

    TEST_ASSERT_EQUAL_DOUBLE(0., IC_ROUND(-0.49));
    TEST_ASSERT_EQUAL(0, IC_REQUIRE_CONSTANT((int) IC_ROUND(-0.49)));
    TEST_ASSERT_EQUAL_DOUBLE(-1., IC_ROUND(-0.5));
    TEST_ASSERT_EQUAL(-1, IC_REQUIRE_CONSTANT((int) IC_ROUND(-0.5)));

    TEST_ASSERT_EQUAL_FLOAT(0.f, IC_ROUND(0.49f));
    TEST_ASSERT_EQUAL(0, IC_REQUIRE_CONSTANT((int) IC_ROUND(0.49f)));
    TEST_ASSERT_EQUAL_FLOAT(1.f, IC_ROUND(0.5f));
    TEST_ASSERT_EQUAL(1, IC_REQUIRE_CONSTANT((int) IC_ROUND(0.5f)));

    TEST_ASSERT_EQUAL_DOUBLE(100000., IC_ROUND(100000.49999999));
    TEST_ASSERT_EQUAL(100000, IC_REQUIRE_CONSTANT((int) IC_ROUND(100000.49999999)));
    TEST_ASSERT_EQUAL_DOUBLE(100001., IC_ROUND(100000.5));
    TEST_ASSERT_EQUAL(100001, IC_REQUIRE_CONSTANT((int) IC_ROUND(100000.5)));

    TEST_ASSERT_EQUAL_DOUBLE(100000.l, IC_ROUND(100000.49999999l));
    TEST_ASSERT_EQUAL(100000, IC_REQUIRE_CONSTANT((int) IC_ROUND(100000.49999999l)));
    TEST_ASSERT_EQUAL_DOUBLE(100001.l, IC_ROUND(100000.5l));
    TEST_ASSERT_EQUAL(100001, IC_REQUIRE_CONSTANT((int) IC_ROUND(100000.5l)));

    TEST_ASSERT_EQUAL_FLOAT(10000.f, IC_ROUND(10000.001f));
    TEST_ASSERT_EQUAL(10000, IC_REQUIRE_CONSTANT((int) (IC_ROUND(10000.001f))));

    TEST_ASSERT_EQUAL_FLOAT(10000.f, IC_ROUND(10000.f));
    TEST_ASSERT_EQUAL(10000, IC_REQUIRE_CONSTANT((int) (IC_ROUND(10000.f))));
}

void test_IC_DIV_ROUND_UP(void) {
    IC_ASSERT_CONSTANT(IC_DIV_ROUND_UP(0, 1));

    TEST_ASSERT_EQUAL(0, IC_DIV_ROUND_UP(0, 1));
    TEST_ASSERT_EQUAL(1, IC_DIV_ROUND_UP(1, 2));
    TEST_ASSERT_EQUAL(2, IC_DIV_ROUND_UP(3, 2));
    TEST_ASSERT_EQUAL(2, IC_DIV_ROUND_UP(8, 4));
}

void test_IC_DIV_ROUND_CLOSEST(void) {
    IC_ASSERT_CONSTANT(IC_DIV_ROUND_UP(0, 1));

    TEST_ASSERT_EQUAL(0, IC_DIV_ROUND_CLOSEST(0, 1));
    /* 5 / 2 = 2.5 -> 3 */
    TEST_ASSERT_EQUAL(3, IC_DIV_ROUND_CLOSEST(5, 2));
    TEST_ASSERT_EQUAL(-3, IC_DIV_ROUND_CLOSEST(5, -2));
    TEST_ASSERT_EQUAL(-3, IC_DIV_ROUND_CLOSEST(-5, 2));
    TEST_ASSERT_EQUAL(3, IC_DIV_ROUND_CLOSEST(-5, -2));
    /* 7 / 3 = 2.(3) -> 2 */
    TEST_ASSERT_EQUAL(2, IC_DIV_ROUND_CLOSEST(7, 3));
    TEST_ASSERT_EQUAL(-2, IC_DIV_ROUND_CLOSEST(-7, 3));
}

void test_IC_MAX(void) {
    IC_ASSERT_CONSTANT(IC_MAX(0, 1));

    TEST_ASSERT_EQUAL(1, IC_MAX(0, 1));
    TEST_ASSERT_EQUAL(0, IC_MAX(0, -1));

    TEST_ASSERT_EQUAL_DOUBLE(1., IC_MAX(0., 1.));
    TEST_ASSERT_EQUAL_DOUBLE(0., IC_MAX(0., -1.));

    TEST_ASSERT_EQUAL_FLOAT(1.f, IC_MAX(0.f, 1.f));
    TEST_ASSERT_EQUAL_FLOAT(0.f, IC_MAX(0.f, -1.f));

    TEST_ASSERT_EQUAL_DOUBLE(1.l, IC_MAX(0.l, 1.l));
    TEST_ASSERT_EQUAL_DOUBLE(0.l, IC_MAX(0.l, -1.l));
}

void test_IC_MIN(void) {
    IC_ASSERT_CONSTANT(IC_MIN(0, 1));

    TEST_ASSERT_EQUAL(0, IC_MIN(0, 1));
    TEST_ASSERT_EQUAL(-1, IC_MIN(0, -1));

    TEST_ASSERT_EQUAL_DOUBLE(0., IC_MIN(0., 1.));
    TEST_ASSERT_EQUAL_DOUBLE(-1., IC_MIN(0., -1.));

    TEST_ASSERT_EQUAL_FLOAT(0.f, IC_MIN(0.f, 1.f));
    TEST_ASSERT_EQUAL_FLOAT(-1.f, IC_MIN(0.f, -1.f));

    TEST_ASSERT_EQUAL_DOUBLE(0.l, IC_MIN(0.l, 1.l));
    TEST_ASSERT_EQUAL_DOUBLE(-1.l, IC_MIN(0.l, -1.l));
}

void test_IC_CLAMP(void) {
    IC_ASSERT_CONSTANT(IC_CLAMP(1, 2, 3));

    TEST_ASSERT_EQUAL(5, IC_CLAMP(5, 3, 7));
    TEST_ASSERT_EQUAL(3, IC_CLAMP(3, 3, 7));
    TEST_ASSERT_EQUAL(7, IC_CLAMP(7, 3, 7));
    TEST_ASSERT_EQUAL(3, IC_CLAMP(1, 3, 7));
    TEST_ASSERT_EQUAL(7, IC_CLAMP(8, 3, 7));
    TEST_ASSERT_EQUAL(-5, IC_CLAMP(-5, -7, -3));
    TEST_ASSERT_EQUAL(-7, IC_CLAMP(-9, -7, -3));
    TEST_ASSERT_EQUAL(-3, IC_CLAMP(1, -7, -3));

    TEST_ASSERT_EQUAL(IC_CLAMP(0xffffffffaULL, 0xffffffff0ULL, 0xfffffffffULL), 0xffffffffaULL);

    TEST_ASSERT_EQUAL_DOUBLE(5., IC_CLAMP(5., 3., 7.));
    TEST_ASSERT_EQUAL_DOUBLE(3., IC_CLAMP(3., 3., 7.));
    TEST_ASSERT_EQUAL_DOUBLE(7., IC_CLAMP(7., 3., 7.));
    TEST_ASSERT_EQUAL_DOUBLE(3., IC_CLAMP(1., 3., 7.));
    TEST_ASSERT_EQUAL_DOUBLE(7., IC_CLAMP(8., 3., 7.));
    TEST_ASSERT_EQUAL_DOUBLE(-5., IC_CLAMP(-5., -7., -3.));
    TEST_ASSERT_EQUAL_DOUBLE(-7., IC_CLAMP(-9., -7., -3.));
    TEST_ASSERT_EQUAL_DOUBLE(-3., IC_CLAMP(1., -7., -3.));
}

void test_IC_IN_RANGE(void) {
    IC_ASSERT_CONSTANT(IC_IN_RANGE(0, 0, 0));

    TEST_ASSERT_TRUE(IC_IN_RANGE(0, 0, 0));
    TEST_ASSERT_TRUE(IC_IN_RANGE(1, 0, 1));
    TEST_ASSERT_TRUE(IC_IN_RANGE(1, 0, 2));
    TEST_ASSERT_TRUE(IC_IN_RANGE(-1, -2, 2));
    TEST_ASSERT_TRUE(IC_IN_RANGE(-3, -5, -1));
    TEST_ASSERT_TRUE(IC_IN_RANGE(0, 0, UINT64_MAX));
    TEST_ASSERT_TRUE(IC_IN_RANGE(UINT64_MAX, 0, UINT64_MAX));
    TEST_ASSERT_TRUE(IC_IN_RANGE(0, INT64_MIN, INT64_MAX));
    TEST_ASSERT_TRUE(IC_IN_RANGE(INT64_MIN, INT64_MIN, INT64_MAX));
    TEST_ASSERT_TRUE(IC_IN_RANGE(INT64_MAX, INT64_MIN, INT64_MAX));

    TEST_ASSERT_FALSE(IC_IN_RANGE(5, 0, 2));
    TEST_ASSERT_FALSE(IC_IN_RANGE(5, 10, 0));
    TEST_ASSERT_FALSE(IC_IN_RANGE(-1, 0, 1));
}

void test_IC_ILOG2(void) {
    IC_ASSERT_CONSTANT(IC_ILOG2((IC_BIT64(63) + 1)));

    TEST_ASSERT_EQUAL(0, IC_ILOG2(1U));
    TEST_ASSERT_EQUAL(1, IC_ILOG2(2U));
    TEST_ASSERT_EQUAL(1, IC_ILOG2(3U));
    TEST_ASSERT_EQUAL(2, IC_ILOG2(4U));
    TEST_ASSERT_EQUAL(2, IC_ILOG2(5U));
    TEST_ASSERT_EQUAL(2, IC_ILOG2(5U));
    TEST_ASSERT_EQUAL(31, IC_ILOG2(IC_BIT(31U)));
    TEST_ASSERT_EQUAL(31, IC_ILOG2(IC_BIT(31U) + 1U));
    TEST_ASSERT_EQUAL(31, IC_ILOG2(UINT32_MAX));
    TEST_ASSERT_EQUAL(32, IC_ILOG2(IC_BIT64(32ULL)));
    TEST_ASSERT_EQUAL(62, IC_ILOG2(IC_BIT64(63U) - 1U));
    TEST_ASSERT_EQUAL(63, IC_ILOG2(IC_BIT64(63U)));
    TEST_ASSERT_EQUAL(63, IC_ILOG2(IC_BIT64(63U) + 1U));
    TEST_ASSERT_EQUAL(63, IC_ILOG2(UINT64_MAX));

    uint8_t const val = IC_ILOG2(42U);
    TEST_ASSERT_EQUAL(5, val);
    uint8_t const val64 = IC_ILOG2(42U + IC_BIT64(32U));
    TEST_ASSERT_EQUAL(32, val64);
}

void test_IC_Z_ILOG2(void) {
    TEST_ASSERT_EQUAL(-1, IC_Z_ILOG2(0U));

    TEST_ASSERT_EQUAL(0, IC_Z_ILOG2(1U));
    TEST_ASSERT_EQUAL(1, IC_Z_ILOG2(2U));
    TEST_ASSERT_EQUAL(1, IC_Z_ILOG2(3U));

    TEST_ASSERT_EQUAL(2, IC_Z_ILOG2(4U));
    uint8_t val = 4;
    TEST_ASSERT_EQUAL(2, IC_Z_ILOG2(val));
    TEST_ASSERT_EQUAL(2, IC_Z_ILOG2(5U));
    TEST_ASSERT_EQUAL(2, IC_Z_ILOG2(5U));
    TEST_ASSERT_EQUAL(31, IC_Z_ILOG2(IC_BIT(31)));
    TEST_ASSERT_EQUAL(31, IC_Z_ILOG2(IC_BIT(31) + 1));
    TEST_ASSERT_EQUAL(31, IC_Z_ILOG2(UINT32_MAX));
    TEST_ASSERT_EQUAL(32, IC_Z_ILOG2(IC_BIT64(32)));
    TEST_ASSERT_EQUAL(62, IC_Z_ILOG2(IC_BIT64(63) - 1));
    uint64_t val64 = IC_BIT64(63) - 1;
    TEST_ASSERT_EQUAL(62, IC_Z_ILOG2(val64));
    TEST_ASSERT_EQUAL(63, IC_Z_ILOG2(IC_BIT64(63)));
    TEST_ASSERT_EQUAL(63, IC_Z_ILOG2(IC_BIT64(63) + 1));
    TEST_ASSERT_EQUAL(63, IC_Z_ILOG2(UINT64_MAX));

    uint8_t const res = IC_Z_ILOG2(42U);
    TEST_ASSERT_EQUAL(5, res);
    uint8_t const res64 = IC_Z_ILOG2(42U + IC_BIT64(32));
    TEST_ASSERT_EQUAL(32, res64);
}

void test_IC_LOG2CEIL(void) {
    IC_ASSERT_CONSTANT(IC_LOG2CEIL(3U));

    TEST_ASSERT_EQUAL(0, IC_LOG2CEIL(0U));
    TEST_ASSERT_EQUAL(0, IC_LOG2CEIL(1U));
    TEST_ASSERT_EQUAL(1, IC_LOG2CEIL(2U));
    TEST_ASSERT_EQUAL(2, IC_LOG2CEIL(3U));
    TEST_ASSERT_EQUAL(2, IC_LOG2CEIL(4U));
    TEST_ASSERT_EQUAL(3, IC_LOG2CEIL(5U));
    TEST_ASSERT_EQUAL(31, IC_LOG2CEIL(IC_BIT(31)));
    TEST_ASSERT_EQUAL(32, IC_LOG2CEIL(IC_BIT(31) + 1));
    TEST_ASSERT_EQUAL(32, IC_LOG2CEIL(UINT32_MAX));
    TEST_ASSERT_EQUAL(32, IC_LOG2CEIL(IC_BIT64(32)));
    TEST_ASSERT_EQUAL(33, IC_LOG2CEIL(IC_BIT64(32) + 1));
    TEST_ASSERT_EQUAL(63, IC_LOG2CEIL(IC_BIT64(63) - 1));
    TEST_ASSERT_EQUAL(63, IC_LOG2CEIL(IC_BIT64(63)));
    TEST_ASSERT_EQUAL(64, IC_LOG2CEIL(IC_BIT64(63) + 1));
    TEST_ASSERT_EQUAL(64, IC_LOG2CEIL(UINT64_MAX));
}

int main(void) {
    UNITY_BEGIN();

    RUN_TEST(test_IC_ABS);
    RUN_TEST(test_IC_IROUND_UP);
    RUN_TEST(test_IC_CEIL);
    RUN_TEST(test_IC_FLOOR);
    RUN_TEST(test_IC_ROUND);
    RUN_TEST(test_IC_DIV_ROUND_UP);
    RUN_TEST(test_IC_DIV_ROUND_CLOSEST);
    RUN_TEST(test_IC_MAX);
    RUN_TEST(test_IC_MIN);
    RUN_TEST(test_IC_CLAMP);
    RUN_TEST(test_IC_IN_RANGE);
    RUN_TEST(test_IC_ILOG2);
    RUN_TEST(test_IC_Z_ILOG2);
    RUN_TEST(test_IC_LOG2CEIL);

    return UNITY_END();
}