name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: |
          sudo apt update
          sudo apt install clang-format
          clang-format --version
      
      - name: Run clang-format
        run: cmake -P lint.cmake
