name: Release
permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: cmake -B build

      - name: Package source code
        run: cmake --build build --target package
        
      - name: Add packaged source code to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ic_macros.zip
          tag: ${{ github.ref }}
