name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Ninja
        run: sudo apt install ninja-build

      - name: Test native
        run: cmake -P test.cmake

      - name: apt update
        run: sudo apt update

      - name: Install Cross Platform Packages
        run: >
          sudo apt install qemu-user qemu-user-static gcc-aarch64-linux-gnu
          g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
      
      - name: Install xPack XPM
        run: npm install --global xpm@latest
      
      - name: Install arm-none-eabi-gcc
        continue-on-error: true
        run: xpm install @xpack-dev-tools/arm-none-eabi-gcc@13.2.1-1.1.1
      
      - name: Install Zephyr SDK
        run: |
          cd ~
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/toolchain_linux-x86_64_arm-zephyr-eabi.tar.xz
          tar -xf toolchain_linux-x86_64_arm-zephyr-eabi.tar.xz
      
      - name: Test arm-none-eabi-gcc
        run: |
          . ./envr.ps1
          cmake -P test.cmake arm-none-eabi-gcc
      
      - name: Test arm-zephyr-eabi-gcc
        run: |
          . ./envr.ps1
          cmake -P test.cmake arm-zephyr-eabi-gcc
      
      - name: Test aarch64-linux-gnu-gcc
        run: cmake -P test.cmake aarch64-linux-gnu-gcc
