set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER "$ENV{TOOLCHAIN_GNU_ARM_NONE_EABI_PATH}/$ENV{TOOLCHAIN_GNU_ARM_NONE_EABI_PREFIX}-gcc")
set(CMAKE_C_COMPILER_WORKS 1)

set(CMAKE_CXX_COMPILER "$ENV{TOOLCHAIN_GNU_ARM_NONE_EABI_PATH}/$ENV{TOOLCHAIN_GNU_ARM_NONE_EABI_PREFIX}-g++")
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_C_FLAGS "--specs=rdimon.specs")
